ALTER TABLE viajes
  ADD COLUMN IF NOT EXISTS eliminado_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS eliminado_por_usuario_id INT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS eliminado_motivo VARCHAR(255) NULL;

ALTER TABLE viaje_tramos
  ADD COLUMN IF NOT EXISTS eliminado_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS eliminado_por_usuario_id INT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS eliminado_motivo VARCHAR(255) NULL;
